Upgrade pygithub from 1.39 to 1.55
It's no longer possible to install version 1.39 via pipenv, as we
run into problems with use_2to3:

```
[pipenv.exceptions.InstallError]: Collecting pygithub==1.39
[pipenv.exceptions.InstallError]:   Using cached PyGithub-1.39.tar.gz (2.6 MB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]:   ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:    command: /Users/christopherashton/.local/share/virtualenvs/upgrade-ruby-version-bCjqChGd/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f8/20cwnq2j4jn4279qsdfh_bcm0002lm/T/pip-install-z6iyuzl4/pygithub_fb9c4f8dfc9c4fecbe9553657b815a7f/setup.py'"'"'; __file__='"'"'/private/var/folders/f8/20cwnq2j4jn4279qsdfh_bcm0002lm/T/pip-install-z6iyuzl4/pygithub_fb9c4f8dfc9c4fecbe9553657b815a7f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/f8/20cwnq2j4jn4279qsdfh_bcm0002lm/T/pip-pip-egg-info-gohx6k76
[pipenv.exceptions.InstallError]:        cwd: /private/var/folders/f8/20cwnq2j4jn4279qsdfh_bcm0002lm/T/pip-install-z6iyuzl4/pygithub_fb9c4f8dfc9c4fecbe9553657b815a7f/
[pipenv.exceptions.InstallError]:   Complete output (1 lines):
[pipenv.exceptions.InstallError]:   error in PyGithub setup command: use_2to3 is invalid.
[pipenv.exceptions.InstallError]:   ----------------------------------------
[pipenv.exceptions.InstallError]: WARNING: Discarding https://files.pythonhosted.org/packages/fd/28/c42bdd56111dae8c622c01af69e6d7f3d3ff0a96ad846f221749701f86b1/PyGithub-1.39.tar.gz#sha256=8a87bc0fbd0b70c2f12911f7f25a493cd13371bc1bbac6c548cc61b69e7d006f (from https://pypi.org/simple/pygithub/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement pygithub==1.39 (from versions: 0.0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.11.1, 1.12.1, 1.12.2, 1.13.0, 1.13.1, 1.14.0, 1.14.1, 1.14.2, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.24.1, 1.25.0, 1.25.1, 1.25.2, 1.26.0, 1.27.1, 1.28, 1.29, 1.30, 1.31, 1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.40a1, 1.40a2, 1.40a3, 1.40a4, 1.40, 1.43, 1.43.1, 1.43.2, 1.43.3, 1.43.4, 1.43.5, 1.43.6, 1.43.7, 1.43.8, 1.44, 1.44.1, 1.45, 1.46, 1.47, 1.50, 1.51, 1.52, 1.53, 1.54, 1.54.0.1, 1.54.1, 1.55)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for pygithub==1.39
ERROR: Couldn't install package: pygithub
```

use_2to3 was dropped in v1.55 in this commit:
https://github.com/PyGithub/PyGithub/commit/fec6034a07677b9978a605dc72ab601f6cd1c1b3